package com.tripnest.auth.controller;
import com.tripnest.auth.dto.*; import com.tripnest.auth.entity.UserAccount; import com.tripnest.auth.exception.ResourceNotFoundException; import com.tripnest.auth.repository.UserAccountRepository;
import jakarta.validation.Valid; import org.springframework.http.*; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.security.oauth2.jwt.Jwt; import org.springframework.web.bind.annotation.*; import java.util.List;
import org.springframework.transaction.annotation.Transactional;
@RestController @RequestMapping("/api/admin/users") public class AdminUserController {private final UserAccountRepository users; public AdminUserController(UserAccountRepository users){this.users=users;}
 @GetMapping @Transactional(readOnly = true) public List<AdminUserResponse> list(){return users.findAll().stream().map(this::map).toList();}
 @PatchMapping("/{userId}/status") @Transactional public AdminUserResponse status(@PathVariable Integer userId,@Valid @RequestBody UpdateUserStatusRequest request,@AuthenticationPrincipal Jwt jwt){UserAccount user=users.findById(userId).orElseThrow(()->new ResourceNotFoundException("User was not found")); if(user.getUserId().equals(((Number)jwt.getClaim("userId")).intValue()))throw new IllegalArgumentException("You cannot change your own administrator status");user.setStatus(request.status());return map(users.save(user));}
 @DeleteMapping("/{userId}") @Transactional public ResponseEntity<Void> delete(@PathVariable Integer userId,@AuthenticationPrincipal Jwt jwt){if(userId.equals(((Number)jwt.getClaim("userId")).intValue()))throw new IllegalArgumentException("You cannot delete your own administrator account"); if(!users.existsById(userId))throw new ResourceNotFoundException("User was not found");users.deleteById(userId);users.flush();return ResponseEntity.noContent().build();}
 private AdminUserResponse map(UserAccount u){return new AdminUserResponse(u.getUserId(),u.getUsername(),u.getEmail(),u.getFirstName(),u.getLastName(),u.getRole().getRoleName(),u.getStatus(),u.getProfileImagePath());}}
