import { useCallback, useEffect, useState } from "react";
import { BadgeIndianRupee, Building2, CalendarDays, Check, ClipboardList, LayoutPanelTop, MapPin, MessageSquare, Package, RefreshCw, Users } from "lucide-react";
import authService from "../services/authService";
import packageService from "../services/packageService";
import transactionService from "../services/transactionService";
import "../css/Dashboard.css";

const today = () => new Date().toISOString().slice(0, 10);
const emptyTrip = { packageId: "", startDate: "", endDate: "", seatsAvailable: "" };
const emptyDestination = { cityName: "", stateName: "" };

function AdminDashboard() {
  const [tab, setTab] = useState("overview");
  const [data, setData] = useState({ users: [], companies: [], pending: [], packages: [], trips: [], bookings: [], payments: [], feedback: [], destinations: [], stats: {} });
  const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(""); const [filter, setFilter] = useState("");
  const [trip, setTrip] = useState(emptyTrip); const [editingTrip, setEditingTrip] = useState(null);
  const [destination, setDestination] = useState(emptyDestination); const [editingDestination, setEditingDestination] = useState(null);

  const load = useCallback(async () => {
    setError("");
    const results = await Promise.allSettled([
      packageService.list(), authService.users(), authService.companies(), authService.pendingCompanies(), packageService.adminDashboard(), packageService.trips(),
      transactionService.allBookings(), transactionService.allPayments(), transactionService.allFeedback(), packageService.adminDestinations(),
    ]);
    const value = (index, fallback) => results[index].status === "fulfilled" ? results[index].value : fallback;
    setData({ packages: value(0, []), users: value(1, []), companies: value(2, []), pending: value(3, []), stats: value(4, {}), trips: value(5, []), bookings: value(6, []), payments: value(7, []), feedback: value(8, []), destinations: value(9, []) });
    if (results.some((item) => item.status === "rejected")) setError("Some data is unavailable. Ensure all five Java services are running, then refresh.");
  }, []);
  useEffect(() => { const timer = window.setTimeout(load, 0); return () => window.clearTimeout(timer); }, [load]);

  const matches = (...text) => text.join(" ").toLowerCase().includes(filter.toLowerCase());
  const mutate = async (key, work, success) => { setBusy(key); setError(""); try { await work(); setMessage(success); await load(); } catch (apiError) { setError(apiError.response?.data?.message || "Unable to complete this action."); } finally { setBusy(""); } };
  const updateUser = (user) => mutate(`user-${user.userId}`, () => authService.updateUserStatus(user.userId, user.status === "ACTIVE" ? "INACTIVE" : "ACTIVE"), `Tourist ${user.status === "ACTIVE" ? "deactivated" : "activated"} successfully.`);
  const deleteUser = (id, label) => { if (window.confirm(`Delete this ${label} permanently?`)) mutate(`delete-${id}`, () => authService.deleteUser(id), `${label} deleted successfully.`); };
  const togglePackage = (travelPackage) => mutate(`package-${travelPackage.packageId}`, () => packageService.update(travelPackage.packageId, { packageName: travelPackage.packageName, description: travelPackage.description, source: travelPackage.source, destination: travelPackage.destination, price: travelPackage.price, status: travelPackage.status === "ACTIVE" ? "INACTIVE" : "ACTIVE" }), `Package ${travelPackage.status === "ACTIVE" ? "deactivated" : "activated"} successfully.`);
  const createTrip = async (event) => { event.preventDefault(); if (trip.startDate < today() || trip.endDate < today() || trip.endDate < trip.startDate) { setError("Trip dates must be today or later, and end date cannot be before start date."); return; } await mutate("new-trip", () => packageService.createTrip({ ...trip, packageId: Number(trip.packageId), seatsAvailable: Number(trip.seatsAvailable) }), "Trip created successfully."); setTrip(emptyTrip); };
  const saveTrip = async (event) => { event.preventDefault(); if (editingTrip.startDate < today() || editingTrip.endDate < today() || editingTrip.endDate < editingTrip.startDate) { setError("Trip dates must be today or later, and end date cannot be before start date."); return; } await mutate(`trip-${editingTrip.tripId}`, () => packageService.updateTrip(editingTrip.tripId, { startDate: editingTrip.startDate, endDate: editingTrip.endDate, seatsAvailable: Number(editingTrip.seatsAvailable), status: editingTrip.status }), "Trip updated successfully."); setEditingTrip(null); };
  const toggleTrip = (item) => mutate(`trip-${item.tripId}`, () => packageService.updateTrip(item.tripId, { startDate: item.startDate, endDate: item.endDate, seatsAvailable: item.seatsAvailable, status: item.status === "CANCELLED" ? "UPCOMING" : "CANCELLED" }), `Trip ${item.status === "CANCELLED" ? "activated" : "cancelled"} successfully.`);
  const setBookingStatus = (booking, bookingStatus) => mutate(`booking-${booking.bookingId}`, () => transactionService.updateBookingStatus(booking.bookingId, bookingStatus), `Booking #${booking.bookingId} updated successfully.`);
  const removeFeedback = (feedbackId) => { if (window.confirm("Delete this feedback permanently?")) mutate(`feedback-${feedbackId}`, () => transactionService.deleteFeedback(feedbackId), "Feedback deleted successfully."); };
  const saveDestination = async (event) => { event.preventDefault(); const current = editingDestination || destination; const work = editingDestination ? () => packageService.updateDestination(editingDestination.destinationId, current) : () => packageService.createDestination(current); await mutate(editingDestination ? `destination-${editingDestination.destinationId}` : "new-destination", work, `Destination ${editingDestination ? "updated" : "created"} successfully.`); setDestination(emptyDestination); setEditingDestination(null); };
  const toggleDestination = (item) => mutate(`destination-${item.destinationId}`, () => packageService.updateDestinationStatus(item.destinationId, !item.active), `Destination ${item.active ? "deactivated" : "activated"} successfully.`);

  const menu = [["overview", "Dashboard Overview", LayoutPanelTop], ["packages", "Package Control", Package], ["destinations", "Destinations", MapPin], ["tourists", "Tourists", Users], ["companies", "Companies", Building2], ["approvals", "Approval Queue", Check], ["trips", "Trip Planning", CalendarDays], ["bookings", "Booking Control", ClipboardList], ["payments", "Payments", BadgeIndianRupee], ["feedback", "Feedback", MessageSquare], ["reports", "Reports", ClipboardList]];
  const Action = ({ children, onClick, danger = false, disabled = false }) => <button disabled={disabled} className={danger ? "suspend-button" : "approve-button"} onClick={onClick}>{children}</button>;

  return <main className="dashboard-page admin-dashboard">
    <header className="dashboard-header"><div><p>Administrator workspace</p><h1>TripNest control centre</h1><span>Manage packages, accounts, trips, bookings and traveller feedback.</span></div><button className="refresh-button" onClick={load}><RefreshCw size={18} /> Refresh</button></header>
    {error && <div className="form-alert error-alert">{error}</div>}{message && <div className="form-alert success-alert">{message}</div>}
    <div className="admin-workspace"><aside className="admin-sidebar">{menu.map(([id, label, Icon]) => <button key={id} className={tab === id ? "active" : ""} onClick={() => { setTab(id); setFilter(""); }}><Icon size={18} />{label}</button>)}</aside>
      <section className="admin-content">
        {tab === "overview" && <><h2>Dashboard overview</h2><section className="admin-summary overview-summary"><Stat label="Total packages" value={data.stats.totalPackages ?? data.packages.length} Icon={Package} /><Stat label="Active packages" value={data.stats.activePackages ?? 0} Icon={Check} /><Stat label="Total users" value={data.stats.totalUsers ?? data.users.length} Icon={Users} /><Stat label="Confirmed value" value={`₹${Number(data.stats.bookingAmount ?? 0).toLocaleString("en-IN")}`} Icon={BadgeIndianRupee} /></section><Analytics stats={data.stats} /></>}
        {tab === "packages" && <><h2>Package control</h2><Search value={filter} onChange={setFilter} placeholder="Search package, company or destination..." />{data.packages.filter((item) => matches(item.packageName, item.companyName, item.destination)).map((item) => <Row key={item.packageId} title={item.packageName} sub={`${item.companyName} · ${item.destination}`} status={item.status}><Action disabled={busy === `package-${item.packageId}`} onClick={() => togglePackage(item)}>{item.status === "ACTIVE" ? "Deactivate" : "Activate"}</Action><Action danger onClick={() => { if (window.confirm("Delete this package permanently?")) mutate(`package-${item.packageId}`, () => packageService.remove(item.packageId), "Package deleted successfully."); }}>Delete</Action></Row>)}</>}
        {tab === "destinations" && <><h2>Destination management</h2><p className="destination-help">Maintain the city and state choices shown to companies and visitors. A destination used by a package can be deactivated, but cannot be deleted.</p><DestinationForm value={editingDestination || destination} setValue={editingDestination ? setEditingDestination : setDestination} submit={saveDestination} editing={Boolean(editingDestination)} cancel={() => setEditingDestination(null)} />{data.destinations.filter((item) => matches(item.cityName, item.stateName)).map((item) => <Row key={item.destinationId} title={item.cityName} sub={item.stateName} status={item.active ? "ACTIVE" : "INACTIVE"}><Action onClick={() => setEditingDestination({ ...item })}>Edit</Action><Action disabled={busy === `destination-${item.destinationId}`} onClick={() => toggleDestination(item)}>{item.active ? "Deactivate" : "Activate"}</Action><Action danger disabled={busy === `destination-delete-${item.destinationId}`} onClick={() => { if (window.confirm(`Delete ${item.cityName}? This cannot be undone.`)) mutate(`destination-delete-${item.destinationId}`, () => packageService.removeDestination(item.destinationId), "Destination deleted successfully."); }}>Delete</Action></Row>)}</>}
        {tab === "tourists" && <><h2>Tourist accounts</h2><Search value={filter} onChange={setFilter} placeholder="Search tourist name or email..." />{data.users.filter((item) => item.role === "TOURIST" && matches(item.username, item.email)).map((item) => <Row key={item.userId} title={item.username} sub={item.email} status={item.status}><Action disabled={busy === `user-${item.userId}`} onClick={() => updateUser(item)}>{item.status === "ACTIVE" ? "Deactivate" : "Activate"}</Action><Action danger onClick={() => deleteUser(item.userId, "tourist")}>Delete</Action></Row>)}</>}
        {tab === "companies" && <><h2>Company accounts</h2><Search value={filter} onChange={setFilter} placeholder="Search company, email or registration no..." />{data.companies.filter((item) => matches(item.companyName, item.email, item.registrationNumber)).map((item) => <Row key={item.companyId} title={item.companyName} sub={`${item.email} · ${item.registrationNumber}`} status={item.status}>{item.status !== "APPROVED" && <Action disabled={busy === `company-${item.companyId}`} onClick={() => mutate(`company-${item.companyId}`, () => authService.approveCompany(item.companyId), "Company activated successfully.")}>Activate</Action>}{item.status === "APPROVED" && <Action danger disabled={busy === `company-${item.companyId}`} onClick={() => mutate(`company-${item.companyId}`, () => authService.suspendCompany(item.companyId), "Company deactivated successfully.")}>Deactivate</Action>}<Action danger disabled={busy === `delete-${item.userId}`} onClick={() => deleteUser(item.userId, "company")}>Delete</Action></Row>)}</>}
        {tab === "approvals" && <><h2>Approval queue</h2>{data.pending.length === 0 ? <p>No company is waiting for approval.</p> : data.pending.map((item) => <Row key={item.companyId} title={item.companyName} sub={item.email} status={item.status}><Action onClick={() => mutate(`company-${item.companyId}`, () => authService.approveCompany(item.companyId), "Company approved successfully.")}>Approve</Action><Action danger onClick={() => mutate(`company-${item.companyId}`, () => authService.suspendCompany(item.companyId), "Company rejected successfully.")}>Reject</Action></Row>)}</>}
        {tab === "trips" && <><h2>Trip planning and control</h2><TripForm value={trip} setValue={setTrip} packages={data.packages} submit={createTrip} label="Create trip" /><h3 className="trip-list-title">Existing trips</h3>{editingTrip && <TripForm value={editingTrip} setValue={setEditingTrip} packages={[]} submit={saveTrip} label="Save trip changes" editing cancel={() => setEditingTrip(null)} />}{data.trips.map((item) => <Row key={item.tripId} title={item.packageName} sub={`${item.startDate} to ${item.endDate} · ${item.seatsAvailable} seats`} status={item.status}><Action onClick={() => setEditingTrip({ ...item })}>Edit</Action><Action disabled={busy === `trip-${item.tripId}`} onClick={() => toggleTrip(item)}>{item.status === "CANCELLED" ? "Activate" : "Deactivate"}</Action><Action danger onClick={() => { if (window.confirm("Delete this trip permanently?")) mutate(`trip-${item.tripId}`, () => packageService.removeTrip(item.tripId), "Trip deleted successfully."); }}>Delete</Action></Row>)}</>}
        {tab === "bookings" && <><h2>Booking control</h2><Search value={filter} onChange={setFilter} placeholder="Search booking, traveller or destination..." />{data.bookings.filter((item) => matches(item.bookingId, item.username, item.packageName, item.destination)).map((item) => <Row key={item.bookingId} title={`#${item.bookingId} · ${item.packageName}`} sub={`${item.username} · ${item.noOfPersons} traveller(s) · ₹${Number(item.totalAmount).toLocaleString("en-IN")}`} status={item.bookingStatus}><Action disabled={item.bookingStatus !== "PENDING" || busy === `booking-${item.bookingId}`} onClick={() => setBookingStatus(item, "CONFIRMED")}>Confirm</Action><Action danger disabled={item.bookingStatus === "CANCELLED" || busy === `booking-${item.bookingId}`} onClick={() => setBookingStatus(item, "CANCELLED")}>Cancel</Action></Row>)}</>}
        {tab === "payments" && <><h2>Recorded payments</h2><Search value={filter} onChange={setFilter} placeholder="Search booking, payment method or reference..." />{data.payments.filter((item) => matches(item.bookingId, item.paymentMethod, item.transactionId)).map((item) => <Row key={item.paymentId} title={`Booking #${item.bookingId} · ₹${Number(item.amount).toLocaleString("en-IN")}`} sub={`${item.paymentMethod.replace("_", " ")} · ${item.transactionId}`} status={item.paymentStatus} />)}</>}
        {tab === "feedback" && <><h2>Feedback moderation</h2><Search value={filter} onChange={setFilter} placeholder="Search traveller, package or comment..." />{data.feedback.filter((item) => matches(item.username, item.packageName, item.comments)).map((item) => <Row key={item.feedbackId} title={`${item.packageName} · ${item.rating}/5`} sub={`${item.username}: ${item.comments}`} status="Published"><Action danger disabled={busy === `feedback-${item.feedbackId}`} onClick={() => removeFeedback(item.feedbackId)}>Delete</Action></Row>)}</>}
        {tab === "reports" && <><h2>Reports</h2><section className="admin-summary overview-summary"><Stat label="Confirmed booking amount" value={`₹${Number(data.stats.bookingAmount ?? 0).toLocaleString("en-IN")}`} Icon={BadgeIndianRupee} /><Stat label="Total bookings" value={data.bookings.length} Icon={ClipboardList} /><Stat label="Recorded payments" value={data.payments.length} Icon={BadgeIndianRupee} /><Stat label="Traveller feedback" value={data.feedback.length} Icon={MessageSquare} /></section><Analytics stats={data.stats} /></>}
      </section>
    </div>
  </main>;
}

function Stat({ label, value, Icon }) { return <article><div className="summary-icon"><Icon size={22} /></div><span>{label}</span><strong>{value}</strong></article>; }
function Analytics({ stats }) { return <section className="analytics-grid"><Chart title="Revenue by month" items={stats.monthlyRevenue} currency /><Chart title="Bookings by status" items={stats.bookingStatus} /><Chart title="Popular destinations" items={stats.popularDestinations} /></section>; }
function Chart({ title, items = [], currency = false }) { const maximum = Math.max(...items.map((item) => Number(item.value)), 1); return <article className="analytics-card"><h3>{title}</h3>{items.length === 0 ? <p>No confirmed data yet.</p> : <div className="chart-list">{items.map((item) => <div className="chart-row" key={item.label}><div><span>{item.label}</span><strong>{currency ? `₹${Number(item.value).toLocaleString("en-IN")}` : item.value}</strong></div><i><b style={{ width: `${(Number(item.value) / maximum) * 100}%` }} /></i></div>)}</div>}</article>; }
function Row({ title, sub, status, children }) { return <article className="company-review-card"><div className="company-info"><h3>{title}</h3><span>{sub}</span></div><div className="company-status"><span>{status}</span></div>{children && <div className="company-actions">{children}</div>}</article>; }
function Search({ value, onChange, placeholder }) { return <input className="admin-filter" value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} />; }
function DestinationForm({ value, setValue, submit, editing, cancel }) { return <form className="profile-form trip-edit-form destination-form" onSubmit={submit}><div className="section-title"><div><p>{editing ? "Edit destination" : "Add a destination"}</p><h3>{editing ? "Update city and state" : "Create an active destination"}</h3></div>{editing && <button type="button" className="cancel-profile-button" onClick={cancel}>Cancel edit</button>}</div><div className="form-grid"><label className="field-group"><span>City</span><input required maxLength="100" value={value.cityName} onChange={(event) => setValue({ ...value, cityName: event.target.value })} placeholder="e.g. Nashik" /></label><label className="field-group"><span>State</span><input required maxLength="100" value={value.stateName} onChange={(event) => setValue({ ...value, stateName: event.target.value })} placeholder="e.g. Maharashtra" /></label></div><button className="approve-button">{editing ? "Save destination" : "Add destination"}</button></form>; }
function TripForm({ value, setValue, packages, submit, label, editing = false, cancel }) { return <form className="profile-form trip-edit-form" onSubmit={submit}>{editing && <div className="section-title"><div><p>Edit existing trip</p><h3>{value.packageName}</h3></div><button type="button" className="cancel-profile-button" onClick={cancel}>Cancel</button></div>}<div className="form-grid">{!editing && <label className="field-group"><span>Active package</span><select required value={value.packageId} onChange={(event) => setValue({ ...value, packageId: event.target.value })}><option value="">Select package</option>{packages.filter((item) => item.status === "ACTIVE").map((item) => <option key={item.packageId} value={item.packageId}>{item.packageName} — {item.destination}</option>)}</select></label>}<label className="field-group"><span>Start date</span><input required type="date" min={today()} value={value.startDate} onChange={(event) => setValue({ ...value, startDate: event.target.value })} /></label><label className="field-group"><span>End date</span><input required type="date" min={value.startDate || today()} value={value.endDate} onChange={(event) => setValue({ ...value, endDate: event.target.value })} /></label><label className="field-group"><span>Seats available</span><input required min="0" type="number" value={value.seatsAvailable} onChange={(event) => setValue({ ...value, seatsAvailable: event.target.value })} /></label></div><button className="approve-button">{label}</button></form>; }
export default AdminDashboard;
