spring.application.name=tripnest-api-gateway
server.port=8080

eureka.client.service-url.defaultZone=${TRIPNEST_EUREKA_URL:http://localhost:8761/eureka/}
eureka.client.healthcheck.enabled=true

spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://tripnest-auth-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**,/api/users/**,/api/admin/users/**,/api/admin/companies/**

spring.cloud.gateway.server.webflux.routes[1].id=crud-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://tripnest-crud-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/packages/**,/api/trips/**,/api/dashboard/**,/api/destinations/**,/api/admin/destinations/**

spring.cloud.gateway.server.webflux.routes[2].id=transaction-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://tripnest-transaction-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/bookings/**,/api/payments/**,/api/wishlist/**,/api/feedback/**

management.endpoints.web.exposure.include=health,info,gateway

spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:5173,http://127.0.0.1:5173
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-headers=Authorization,Content-Type
spring.cloud.gateway.server.webflux.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials RETAIN_FIRST
